[package]
name = "aso_scramble_check"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.4", features = ["derive"]}
env_logger = "0.11.3"
log = { version = "0.4.21"}
csv = {version =  "1.3.0" }
distance = {version = "0.4" }